version: "3"

services:
  db:
    container_name: sapphire_db
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./back/tmp/db:/var/lib/msql

  back:
    container_name: sapphire_back
    build: back/
    volumes:
      - ./back:/app
    depends_on:
      - db

  front:
    container_name: sapphire_front
    build: front/
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 8080:3000
